name: CI

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                typo3: [ 12.4 ]
                php: [ 8.4 ]

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v6

            -   name: Setup PHP
                uses: https://github.com/shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}

            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Get composer cache directory
                id: composer-cache
                run: |
                    echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            -   uses: actions/cache@v5
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-${{ matrix.php }}-${{ matrix.typo3 }}-composer-${{ hashFiles('**/composer.json') }}
                    restore-keys: |
                        ${{ runner.os }}-${{ matrix.php }}-${{ matrix.typo3 }}-composer-

            -   name: Install dependencies
                run: |
                    composer install --prefer-dist --no-interaction --no-progress

            -   name: Lint
                if: ${{ success() }}
                run: composer ci:test:php:lint

            -   name: Unit Tests
                if: ${{ success() }}
                run: composer ci:test:php:unit

            -   name: Functional Tests
                if: ${{ success() }}
                run: composer ci:test:php:functional

            -   name: CGL
                if: ${{ success() }}
                run: composer ci:test:php:cgl

            -   name: PHPStan
                if: ${{ success() }}
                run: composer ci:test:php:phpstan -- --error-format=table

            -   name: Rector
                if: ${{ success() }}
                run: composer ci:test:php:rector

            -   name: Fractor
                if: ${{ success() }}
                run: composer ci:test:php:fractor
